filter:
    excluded_paths:
        - 'test/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    nodes:
        analysis:
            project_setup:
                override: ['true']
            tests:
                override: [php-scrutinizer-run]
        tests: true
            override:
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'